### ISSUE TITLE
chore: add codeowners file

### ISSUE THREAD

**Issue by schalkneethling** [The-Mycelium-Network/bookclub#28]
I figured it out!! So, when you set up [auto assignment alone](https://docs.github.com/en/organizations/organizing-members-into-teams/managing-code-review-settings-for-your-team#about-auto-assignment), people are not automatically assigned as I thought. If you go to a pull request and choose the team as the "reviewer," GitHub will use the algorithm selected to select a member from the team. GitHub will then unassign the team and assign the individual.

Now, if we setup a [`CODEOWNERS`](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners) file and set the team as the code owner for everything in the repo, GitHub will auto-assign the team to all pull requests. That will then trigger the above, resulting in an individual being assigned.

For now I _think_ we are ok with an individual but, as the rate of pull requests increases across repositories, we should change this to assign two people. When can then set a branch protection rule that only requires one of the assignees to approve the pull request.

That will reduce the possible strain on individuals.

**Comment by bpires** [comment]
Glad you figured out!
