### ISSUE TITLE
docs: add more details to 'Working the Command Line' README

### ISSUE THREAD

**Issue by bpires** [The-Mycelium-Network/bookclub#5]
- [x] Add about the book
- [x] Add about the author
- [x] Add about the sponsor
- [x] Include a list of participants
- [x] Include visual aids
- [x] Create a banner
- [x] Keep it light-hearted and fun

**Comment by bpires** [comment]
@schalkneethling, please feel absolutely free to change anything on PR #6, including removing or using a new banner. I'm pointing this out because I know that you take copyrights and author attribution very seriously (and me too, but I'm still learning to have more vigilance with that). 

In my last version, I made a reference for the photo origin, but it's actually just a photo of a framed print on sale on Etsy. Don't really know if it's off-limits to use it, but I've sent a message to the print artist to check if it is ok.

This has been a playful way to learn while contributing. For instance, I've just learned about checking boxes and completing tasks on issues on GitHub. ✔️ All the interaction here can make us “early-stagers” more familiar with Git/GH tools.

PS: Wasn't sure if this kind of open dialogue was more suitable for the PR or for the Issue comments. Please let me know if you have any feedback on open-source etiquette. :)

**Comment by schalkneethling** [comment]
@bpires Thanks so much for your input.

> In my last version, I made a reference for the photo origin, but it's actually just a photo of a framed print on sale on Etsy. Don't really know if it's off-limits to use it, but I've sent a message to the print artist to check if it is ok.

Thank you for mentioning this, we should indeed be careful. I tend to always go to https://unsplash.com to find imagery and copy the attribution once I have decided which one to use. I love that you jumped in and got creative with all of this. For the banner, perhaps we can make a template we can easily reuse for the various books. I can start something in Figma that I can share with everyone so we can work on the designs together.

>This has been a playful way to learn while contributing. For instance, I've just learned about checking boxes and completing tasks on issues on GitHub. ✔️ All the interaction here can make us “early-stagers” more familiar with Git/GH tools.

Love it 🙌 

> PS: Wasn't sure if this kind of open dialogue was more suitable for the PR or for the Issue comments. Please let me know if you have any feedback on open-source etiquette. :)

Not so much an etiquette thing but, I reckon in this instance this comment would feel more at home one the pull request itself 😄

**Comment by bpires** [comment]
I liked the idea of a template on Figma, that's something near to what I had in mind. Anyway, this is just a little flourish to make the readme more friendly, if prefer to keep it plain text, just let me know. I'm sensing you have plans to incorporate the content of the bookclub in a section on webworkbook maybe?

PS: The photo author said it was totally fine and the project looks cool ;)
